### PR TITLE
Create an MkDocs Wiki

### PR DESCRIPTION
**Pull request by halotroop2288**
The goal of this PR is to provide more substantial and accurate documentation for Jankson users.

I started by rewriting the existing pages from the GitHub wiki in a way that explains Java, Kotlin, and Groovy all at once, with instructions for use with both Gradle (under both Groovy DSL and Kotlin DSL) and Apache Maven.

### CODE REVIEW

**Comment by halotroop2288** [comment]
To test this PR, run `python -m pip install mkdocs mkdocs-material && mkdocs serve`

**Comment by halotroop2288** [comment]
I have no idea how to sign my commits. I think I've only ever attempted it once and decided it wasn't worth the effort after that.

**Comment by falkreon** [comment]
> I have no idea how to sign my commits. I think I've only ever attempted it once and decided it wasn't worth the effort after that.

Sounds like you've done all the steps besides asking git to globally GPG-sign commits - https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

It's a lengthy process but you should only ever have to do it once.

**Comment by falkreon** [comment]
The docs look fantastic, thanks for making these! I'm bypassing branch protections to merge this one because we really need it.

**Comment by halotroop2288** [comment]
Glad to be of service.

**Pull request merged**
